#!/usr/bin/env tsx
/**
 * Regenerate src/templates/tokens.ts from a live Plasmic project's style tokens.
 *
 *   npm run gen:tokens [-- <projectId>]
 *
 * Project resolution: argv[2] > PLASMIC_TOKENS_PROJECT > the Aita design-system
 * project. The generated file is a committed snapshot so unit tests run offline;
 * plasmic_insert_template additionally validates against the LIVE token list at
 * insert time, so a stale snapshot fails loud, not silent.
 *
 * varName is the kebab-cased token name. Studio's web importer matches
 * `var(--token-<x>)` refs with toVarName() (lodash camelCase) applied to BOTH
 * sides, so kebab-case and the original name normalize identically.
 */
import { config as loadEnv } from "dotenv";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { writeFileSync } from "node:fs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
loadEnv({ path: join(root, ".env") });

import { PlasmicClient } from "../src/client.js";
import { toKebabVarName } from "../src/templates/token-names.js";

const DEFAULT_TOKENS_PROJECT = "sG6vJRAEtrLuNL7jYb3Tpk"; // Aita design-system tokens

interface ApiToken {
  uuid: string;
  name: string;
  type: string;
  value: string;
  isRegistered?: boolean;
}

async function main(): Promise<void> {
  const projectId =
    process.argv[2] ?? process.env.PLASMIC_TOKENS_PROJECT ?? DEFAULT_TOKENS_PROJECT;
  const host = process.env.PLASMIC_HOST;
  const email = process.env.PLASMIC_EMAIL;
  const password = process.env.PLASMIC_PASSWORD;
  if (!host || !email || !password) {
    throw new Error("PLASMIC_HOST / PLASMIC_EMAIL / PLASMIC_PASSWORD must be set");
  }

  const client = new PlasmicClient({
    host,
    email,
    password,
    userAgent: process.env.PLASMIC_USER_AGENT,
  });
  const res = await client.get<{ tokens: ApiToken[] }>(
    `/api/v1/projects/${encodeURIComponent(projectId)}/tokens`
  );
  const tokens = [...(res.tokens ?? [])].sort((a, b) => a.name.localeCompare(b.name));
  if (tokens.length === 0) {
    throw new Error(`project ${projectId} has no style tokens — wrong project?`);
  }

  const dupes = new Map<string, string[]>();
  for (const t of tokens) {
    const v = toKebabVarName(t.name);
    dupes.set(v, [...(dupes.get(v) ?? []), t.name]);
  }
  for (const [v, names] of dupes) {
    if (names.length > 1) {
      throw new Error(`varName collision "${v}": ${names.join(", ")}`);
    }
  }

  const rows = tokens
    .map((t) => {
      const varName = toKebabVarName(t.name);
      return `  { name: ${JSON.stringify(t.name)}, varName: ${JSON.stringify(varName)}, type: ${JSON.stringify(t.type)}, value: ${JSON.stringify(t.value)}, uuid: ${JSON.stringify(t.uuid)} },`;
    })
    .join("\n");

  const out = `/**
 * AUTO-GENERATED by scripts/gen-tokens.ts — do not edit by hand.
 * Source: ${host} project ${projectId} (${tokens.length} tokens).
 * Regenerate: npm run gen:tokens
 */
import type { DsToken } from "./token-names.js";

export const TOKENS_PROJECT_ID = ${JSON.stringify(projectId)};

export const DS_TOKENS: readonly DsToken[] = [
${rows}
];

/** Kebab-case var names usable as \`var(--token-<varName>)\` in pasted HTML. */
export const TOKEN_VARS: ReadonlySet<string> = new Set(DS_TOKENS.map((t) => t.varName));
`;

  const dest = join(root, "src", "templates", "tokens.ts");
  writeFileSync(dest, out);
  process.stdout.write(`wrote ${dest}: ${tokens.length} tokens from ${projectId}\n`);
}

main().catch((e) => {
  process.stderr.write(`gen-tokens failed: ${(e as Error)?.message ?? e}\n`);
  process.exit(1);
});
